version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: iarc-directory-drupal
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/sites/all
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: iarc-directory
      DB_USERNAME: app
      DB_PASSWORD: app
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: iarc-directory
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: password
